- name: Project B CICD build
  hosts: all
  tasks:
    - name: Project B build task
      debug:
        msg: "Project B test task"
    - name: Project B test trigger
      command: /usr/bin/curl -s -k --data "host_config_key=184657fb599426c589363658a05aa83e" https://ansible.192.168.56.60.nip.io:443/api/v1/job_templates/19/callback/