
- name: Red Hat Insights
  hosts: all
  tasks:
    - name: Ensure insights is installed
      yum:
        name: redhat-access-insights
        state: present
    - name: Register system to insights
      command: redhat-access-insights --register
