- name: Install the apache web server and ensure it's running
  hosts: all
  tasks:
    - name: Install Apache web server
      yum:
        name: httpd
        state: installed
        
    - name:  Ensure Apache web server is running
      service:
        name: httpd
        state: running
        enabled: yes
        
