- name: Install the apache web server and ensure it's running
  hosts: all
  tasks:
    - name: Install Apache web server
      yum:
        name: httpd
        state: installed
        
    - name:  Ensure Apache web server is running
      service:
        name: httpd
        state: started
        enabled: yes
        
    - name: Enable http firewall rule for web server
      firewalld:
        zone: public
        service: http
        permanent: yes
        state: enabled
        
    - name: Enable https firewall rule for web server
      firewalld:
        zone: public
        service: https
        permanent: yes
        state: enabled
        
