- name: Create OCP resources for development team
  hosts: all
  tasks:
    - name: Login to cluster
      command: oc login --insecure-skip-tls-verify --token={{ token }} {{ ocp_server }}
      register: ocp_login
      
    - name: Create project
      command: oc new-project appx-{{ item }}
      when: "ocp_login.rc == 0"
      with_items:
        - dev
        - test
        - prod
        
    - name: Create app in appx-dev
      command: oc new-app --name appx --image-stream=php:7.0 --code=https://github.com/mglantz/ocp-jenkins.git -n appx-dev
      
    - name: Expose service in appx-dev
      command: oc expose service appx -n appx-dev
      
    - name: Associate appx-dev service account to test and prod projects
      command: oc policy add-role-to-group system:image-puller system:serviceaccounts:appx-{{ item }}:default -n appx-dev
      with_items:
        - test
        - prod
        
    - name: Follow the appx-dev container build
      command: oc logs -f appx-1-build -n appx-dev
        
    - name: Allow 10 seconds for pod to come online
      command: sleep 10
      
    - name: Create TEST tag
      command: oc tag appx:latest appx:TESTready -n appx-dev
      
    - name: Create PROD tag
      command: oc tag appx:latest appx:PRODready -n appx-dev
      
    - name: Add access for Jenkins pod to projects
      command: oc policy add-role-to-user edit system:serviceaccount:appx-dev:jenkins -n appx-{{ item }}
      with_items:
        - dev
        - test
        - prod
    
    - name: Deploy Jenkins with pipeline
      command: oc create -f https://raw.githubusercontent.com/mglantz/ocp-jenkins/master/pipeline.yaml -n appx-dev
      
    - name: Deploy app in test
      command: oc new-app --name appx --image-stream=appx-dev/appx:TESTready -n appx-test
      
    - name: Deploy app in prod
      command: oc new-app --name appx --image-stream=appx-dev/appx:PRODready -n appx-prod
      
    - name: Expose services in test and prod
      command: oc expose service appx -n appx-{{ item }}
      with_items:
        - test
        - prod
