- name: Patch Red Hat Enterprise Linux system
  hosts: all
  tasks:
    - name: Update all RPM packages
      yum:
        name: '*'
        state: latest
    - name: Reboot system the system
      command: /sbin/shutdown -r +1
      async: 0
      poll: 0
      ignore_errors: true
