- name: Patch Red Hat Enterprise Linux system
  hosts: all
  tasks:
    - name: Update all RPM packages
      yum:
        name: '*'
        state: latest
      become: yes
      register: patched
    - name: Reboot the system when software has been updated
      reboot:
      when: rebooting|changed
    - name: Wait for server to reboot
      wait_for:
        port: 22
        search_regex: OpenSSH
      vars:
        ansible_connection: local
