- name: Troubleshoot a Linux server
  hosts: all
  tasks:  
    - name: Ping server
      ping:
        data: pong

    - name: Gather login information
      shell: last|grep -v wtmp|grep -v reboot|grep ec2-user|grep "$(date +"%a %b %d")"
      register: login_detect

    - name: Detect if someone logged in to the system today (will get skipped if NOT)
      when: login_detect.stdout.find('0') != -1
      debug:
        msg: "Detected login: {{ login_detect.stdout }}"
  
    - name: Gather information about application crashes
      shell: abrt-cli status
      register: crashes_detected
      become: yes
      
    - name: Detect application crashes (will get skipped if it's OK)
      when: crashes_detected.stdout.find('0') != -1
      debug:
        msg: "Detected {{ crashes_detected }} recent application crashes"
   
    - name: Get CPU usage
      shell: "top -b -n 1"
      register: top
      
    - name: Set CPU usage facts
      set_fact:
        user_cpu: "{{top.stdout_lines[2].split()[1]}}"
        system_cpu: "{{top.stdout_lines[2].split()[3]}}"

    - name: Output CPU usage facts
      debug:
        msg:
          - "User CPU usage: {{user_cpu}}"
          - "System CPU usage: {{system_cpu}}"
